apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::648505502080:role/setrass-ecms-aws-eks-node-group-role
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::648505502080:user/rolando_zavala
      username: rolando_zavala
      groups:
      - system:masters
    - userarn: arn:aws:iam::648505502080:user/marvin_toro
      username: marvin_toro
      groups:
      - system:masters

    - userarn: arn:aws:iam::648505502080:user/alfredo_reyes
      username: alfredo_reyes
      groups:
      - system:bootstrappers
      - system:nodes
      - eks-console-dashboard-full-access-group  

    - userarn: arn:aws:iam::648505502080:user/angel_diaz
      username: angel_diaz
      groups:
      - system:bootstrappers
      - system:nodes
      - eks-console-dashboard-full-access-group  

    - userarn: arn:aws:iam::648505502080:user/jorge_aguilar
      username: jorge_aguilar
      groups:
      - system:bootstrappers
      - system:nodes
      - eks-console-dashboard-full-access-group 

    - userarn: arn:aws:iam::648505502080:user/nicolle_salazar
      username: nicolle_salazar
      groups:
      - system:bootstrappers
      - system:nodes
      - eks-console-dashboard-full-access-group

    - userarn: arn:aws:iam::648505502080:user/rolando_test
      username: rolando_test
      groups:
      - system:bootstrappers
      - system:nodes
      - eks-console-dashboard-full-access-group      


kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
